install(
  FILES
    Array.hpp
    Bag.hpp
    BaseSequence.hpp
    CMakeLists.txt
    Common.hpp
    EnumSet.hpp
    Hasher.hpp
    HSequence.hpp
    Interface.hpp
    IV.hpp
    MArray.hpp
    MEnumSet.hpp
    MSequence.hpp
    Multibag.hpp
    Multimap.hpp
    PSequence.hpp
    Range.hpp
    Scalar.hpp
    Sequence.hpp
    Set.hpp
    Skynet.hpp
  DESTINATION
    ${DT_INSTALL_DIR}/include/skynet
)